language: rust
sudo: required
dist: trusty
rust:
  - nightly
services:
  - docker
script:
  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      sh ci/run-travis.sh;
    else
      cargo build;
    fi
os:
  - linux
env:
  matrix:
    - ARCH=x86_64
  global:
    secure: eIDEoQdTyglcsTD13zSGotAX2HDhRSXIaaTnVZTThqLSrySOc3/6KY3qmOc2Msf7XaBqfFy9QA+alk7OwfePp253eiy1Kced67ffjjFOytEcRT7FlQiYpcYQD6WNHZEj62/bJBO4LTM9sGtWNCTJVEDKW0WM8mUK7qNuC+honPM=
matrix:
  include:
    - os: linux
      env: TARGET=mips-unknown-linux-gnu DOCKER=plhk/ubuntu-cross-mips:latest CC=mips-linux-gnu-gcc
      rust: nightly
notifications:
  email:
    on_success: never
branches:
  only:
    - master
